### PR TITLE
AUTHORS file

### PR DESCRIPTION
**Pull request by markotoplak**
List of authors per #217

I added people that appeared in git and added their institutions. 

Please review. @GioB81, @achimkohler, @borondics, @stuart-cls

### CODE REVIEW

**Comment by GioB81** [comment]
Hi,

It is ok, only one thing...

I know that we did not contribute actively in coding, so far, but it will
be important for Elettra to be at least mentioned as a partner.

so something like acknowledging institutions and authors + their
institution in the same list

best,

Gio

**Comment by borondics** [comment]
Hi Everyone,

I have a few things to add. 

Since this is an open source project we have contributors who do coding on their own time, people who do it on work time and organizations who pay for those working hours. The ultimate case of funding, when someone was hired only to work on the Orange Spectroscopy project happened only twice, the first time SOLEIL+ELETTRA+Biolab and the second time SOLEIL. **All** these **contributions** should and **will be acknowledged**.

Suggestion:
In the AUTHORS file simply provide a link to https://github.com/Quasars/orange-spectroscopy/graphs/contributors, which is updated automatically, so everyone is acknowledged personally according to their merits. For the organizations we should add sections for each toolbox we include in Quasar on the website with appropriate links and/or logos.

Feri

**Comment by borondics** [comment]
Let's build the AUTHORS file with this command:

`git shortlog -sne >AUTHORS`

Question: can we do it automatically after each commit somehow?

**Comment by markotoplak** [comment]
I do not think we need this list if we have https://github.com/Quasars/orange-spectroscopy/graphs/contributors and https://quasar.codes

I would just close this PR. What to you think?

**Comment by borondics** [comment]
OK for me.

**Pull request closed without merging**
