### PR TITLE
Fixes DeprecationWarning for importing from collections

### PR DESCRIPTION
**Pull request by borondics**
Based on https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7

### CODE REVIEW

**Comment by markotoplak** [comment]
Because we only support Python>=3.6, we probably do not need to try/catch, just importing from collections.abc should work.

**Comment by markotoplak** [comment]
Cool, tests passed even with a simple solution. Could you please squash these two commits into one?

**Comment by borondics** [comment]
I tried... :D Not sure if this is what you meant.

**Comment by markotoplak** [comment]
Not exactly. What you see now is what I meant. So you almost did the correct thing, but I suspect that github complained at pushing and then you first merged and then pushed... Next time try force pushing when you rewrite history (`git push -f whatever_arguments`).

**Pull request merged**
