### PR TITLE
[NOMERGE][WIP] Tests for irfft calcuations (agilent data)

### PR DESCRIPTION
**Pull request by stuart-cls**
Some irfft calculation tests (#252) which compare the results to the stored single channel and absorbance data in our existing test data. There is one new dataset to provide a background file to compare the entire IFG -> SC -> AB calculation.

Currently the single channels match nicely only if they are normalized: there is a scaling factor that I haven't been able to track down. Note that this has no effect on the final AB calculation as long as both sample and reference are calculated the same way (which they ought to be).

### CODE REVIEW

**Comment by stuart-cls** [comment]
Clones #268 which I closed by mistake...

**Comment by stuart-cls** [comment]
Still contains a temporary fix for #265, so don't merge.

**Comment by markotoplak** [comment]
@stuart-cls, were planning to add anything else to this PR? If not, feel free to merge.

**Comment by stuart-cls** [comment]
It's not perfect but it's more useful than nothing!

**Pull request merged**
