### PR TITLE
Unify transformations in one preprocessor

### PR DESCRIPTION
**Pull request by borondics**
With more and more conversions coming (and not only IR, I hope) this will be necessary to keep the main drop-down menu uncluttered and also allow adding conversions easily.

### CODE REVIEW

**Comment by borondics** [comment]
There is no test for the actual calculation though. Should we handle this dynamically or hard-code each transformation?

**Comment by markotoplak** [comment]
If our goal is not to clutter the widget I agree with joining transformations in the widget.

But I think that in the scripting part (preprocess.py) it is clearer if each kind of transformation is in its own class. If there are lots of common computation we can make a superclass that does the repeated stuff.

Of course, as you say, additional tests that actually test the computation would be useful.

**Comment by stuart-cls** [comment]
I agree with @markotoplak that it doesn't make sense to add complexity to the scripting interface. Please keep the preprocessors the way they are.

If you want to combine the graphical interface, I am fine with that.

**Comment by borondics** [comment]
@markotoplak @stuart-cls, I also like the way the GUI and the calculations are separated in principle, but then we need to solve the issue of varying data ranges and the way the GUI learns about the data to properly initialize the GUI elements. I am sure I can hack something together, but maybe it can be done properly as well. 

How should this be done in your opinion?

**Comment by stuart-cls** [comment]
@borondics did you see my response in #131 ? Initializing the GUI with sample data is already possible (and done for many Editors)

**Comment by borondics** [comment]
OK, I'll check it out!

**Pull request closed without merging**
