### PR TITLE
[ENH] s-SNOM Complex FFT Processing

### PR DESCRIPTION
**Pull request by levandoskije**
Enhancement for FFT Processing as mentioned by @stuart-cls in issue #416 .
A new method for complex FFT with GSF files, read by Reader #392 .

-  [x] Processing complex interferograms
-  [ ] Tests for complex processing results

### CODE REVIEW

**Comment by levandoskije** [comment]
@markotoplak and @stuart-cls, I tried  make `git rebase master`, but I has some difficult and I am afraid broken the code.
Any suggestions?

**Comment by stuart-cls** [comment]
Hi @levandoskije 
I've started looking at this today. Don't worry about updating it so it can be merged for now.

**Comment by stuart-cls** [comment]
First, thanks for this contribution. I appreciate that you've worked hard to incorporate your calculations into the very convoluted mess that was already there.

In general, I would like to use this opportunity to improve the calculations / code simplicity for everyone. I understand that you've probably been using this code in your work already, and want the calculations to stay identical. So I think the first and most important step is to define some tests. I propose storing the spectral output of the current code run against the test data and checking any changes against that. But if you have a different test you would prefer, that's fine too.

I'm going to get into the details now, but what I'd like to do is split these changes up into separate commits/pieces. Here are the how I see the changes:

## 1. General structure
A. Setup calculation based on input data
  - This is where we look at the dataset and prepare the widget for calculation, but don't actually do the calculation. Any code that changes calculation parameters or GUI values must be done here. I think everything like this in this PR should go in OWFFT.check_metadata(). It can be restructured as required.

B. Prep Data 
  - This is where we go from Orange.Table to something IRFFT can process. I want to separate this out, but currently this is done in OWFFT.calculateFFT()
    - Currently this handles things like double-sweep data, stored phase, and multirow processing
    - This is where your amplitude+phase combination should go (as you've done)

C. FFT
   - The actual FFT. I'd like to make your complex version an inherited class instead of a different function, but the devil is in the details, which is most of what the rest of this is about.
 
## 2. dx (step size) calculation

 - Do this once, in check_metadata() so users can see the value before calculating
 - This should output the value in cm, not microns
 

## 3. Data Rearrangement (combine amplitude and phase)

A one-liner that does this:
````
    sh_data = self.data.X
    full_data = sh_data[::2] * np.exp(sh_data[1::2] * 1j)
````	
Also, I wonder if it makes more sense to change the arrangement of the data
to be less fragile: the current code requires the data to always be carefully ordered.
We already have the case of dual-sweep interferograms which are split and then processed, I propose building the table as np.hstack(amplitude, phase) and then combining in the calculation. This keeps the paradigm of one row, one sample. We can do this in a separate PR though.

## 4. Peak search / zero-fill

 - Why re-implement this? I'd rather use a single code path unless you have a strong reason not to.
 - The code should respect the user's zff setting. If you must, set the default to 4 in your check_metadata step.
 - Excuse my ignorance, but doesn't s-SNOM use an externally determined zpd value anyway? Peak search is always fragile for weak signals, I'm aiming to move away from it as default when a known value is already present in the metadata.
 - This is not really zero-filling so much as throwing away the low-res side of the interferogram. What the existing code does instead is rotate the array so that the zpd is at the edges, which also gives a flat phase response. Comment?
 
## 5. Apodization / windowing

 - Any particular reason to use the scipy implementation here? I've tried to keep this module numpy-only and we already have an implementation which respects assymetric interferograms (very common in FT-IR as well). If there is some problem with the implementation, we should fix it instead of having two code paths
 
## 6. np.fft.fft vs np.fft.rfft

 - This is obviously the main difference. The only comment here is that using n to zero-fill here instead of the existing code doesn't gaurentee a DFT-efficient array size, which is why I don't use that.

## 7. magnitude / angle

 - This is just a different way of outputting the complex result of the fft, so I'd rather fold it in with that code and make it general. Someone else might like magnitude/angle output for their FTIR data as well.

## 8. Wavenumber calculations

  - Why not just use np.fft.fftfreq(Nzff, self.dx)?

Again, thanks for your hard work so far. I would suggest that you take the current master and add your code with this feedback on to that manually. It will be much easier than trying to rebase and then rearrange. If this is too much work / you don't have time, I can do it.

If you really just want to get this in as close to your existing code as possible, please just focus on suggestions 1-3 and we can discuss unifying the code in for steps 4-7 in a separate PR.

**Comment by levandoskije** [comment]
Hi, @stuart-cls,  thank you for the review!
I will close this PR and do another one with the suggestions above.
The discussion is here #416.

**Pull request closed without merging**
