### PR TITLE
[ENH] More responsive Preprocess and Integrate widgets; progress bars

### PR DESCRIPTION
**Pull request by markotoplak**
Towards fixing #44

### CODE REVIEW

**Comment by markotoplak** [comment]
With the current change the preprocess widget moves the computation into another thread, which means it does not block the user interface.

Currently, it is only interruptible between chain of preprocessors. For more we will need to add callback support to preprocessors. And then we might even clone #289 for ever.

@stuart-cls, I'll appreciate it a lot if you play around with this a bit. It is hard not to introduce bugs while doing this.

**Comment by markotoplak** [comment]
Previews are also interruptible now. The widget should be more responsive in general, and should stay responsive even if working with slow preprocessors, such as me-EMSC.

@borondics and @stuart-cls, try to crash it, please.

**Comment by borondics** [comment]
I think this is a great addition and also very important to be more interactive.

However, there are a few things that came to my mind while playing with it.
- It is not clear how to interrupt the calculation of the preprocessor (at least I couldn't see it).
- The user can make modifications to the preprocessor parameters, even delete them while the preprocessing is running.
- If a preprocessor is running it is still possible to add widgets to the Canvas, but they don't do anything. This defeats the purpose a little bit, although I see that the previously added and finished widgets are still opening and are somewhat responsive, but there can be conflicts I guess.

So far it didn't crash. :)

**Comment by markotoplak** [comment]
@borondics, thanks for trying it out! If not crashing is a very good sign.

Yes, their is no interrupt button - currently, things are interrupted only implicitly when you give new input or change parameters. We could easily add a button though: it is one line of cure.

Now, computation can only be interrupted between different preprocessors; to make it denser, we will need to modify some Orange internals

After I fix tests this will be ready for merging. I'll come back to this after we make improvements in Orange. My next stop: PCA widget.

**Comment by markotoplak** [comment]
@borondics, you expressed a concern about for example deleting a preprocessor (or changing parameters) while it is being computed. In such cases, the current computation gets invalidated as soon as possible (and absolutely never gets to the output of the widget). The new computation is started as soon as the old one managed to be interrupted. At least that was what I tried to do.

**Comment by stuart-cls** [comment]
This is very nice :)


I found one weird thing so far while trying to break it with the "Integrate" widget:
(But it turned out to be very hard to reproduce and is probably a weird Windows edge case, nothing actually crashes)

1. With 150k row dataset connected and Commit Automatically deselected,
2. Add about 5 peak features, including a few peak areas
3. Add some visualizations but leave one peak area hidden
4. Select Commit Automatically
5. While the computation is running, select the visualization of the peak area
6. The widget GUI minimizes itself at some point and can't be restored until the calculation finishes

This was hard to reproduce, I had to restart Orange a few times to clear some cache or something. I also noticed that it triggers the "Not Responding" title bar when this happens.

Maybe a race between multiple preview visualizations and the main calculation?

**Comment by markotoplak** [comment]
@stuart-cls, thanks for testing!

Currently, Table.transform() is limited to 1 concurrent thread (it calls Table.from_table which is surrounded by a Lock), because it uses some kind of global cache. Therefore, if integrals for a bit data set are being computed, preview will wait until that operation is finished.

We will need to remove that lock from Table.from_table. Still, I think this PR, while imperfect, is a step in the right direction.

**Comment by stuart-cls** [comment]
> We will need to remove that lock from Table.from_table. Still, I think this PR, while imperfect, is a step in the right direction.

I completely agree! It works really well and is a big improvement. Thanks for your hard work on it.

**Pull request merged**
