### PR TITLE
[ENH] STXM stack aligner

### PR DESCRIPTION
**Pull request by markotoplak**
Moved from Quasars/orange-spectroscopy-prototypes#3

### CODE REVIEW

**Comment by markotoplak** [comment]
For this to work we need another big dependency: scikit-image. It would increase installers by 25MB.

Also, @stuart-cls, what happens if you try to install this library with pip on Windows? Conda would probably work fine, I guess.

**Comment by borondics** [comment]
Can we just take that function from scikit-image that is used?

**Comment by markotoplak** [comment]
@borondics, I am quite surprised to say, that, yes, in this case we could actually take just that function (it is pure python, no other dependencies than numpy or scipy). Thanks for the suggestion!

**Comment by markotoplak** [comment]
Stuart, thank you!

**Pull request merged**
