### PR TITLE
Changed initialization of the limit lines in Preprocess Spectra/Cut

### PR DESCRIPTION
**Pull request by borondics**
…tra/Cut

### CODE REVIEW

**Comment by stuart-cls** [comment]
Hi Feri!

Can you explain why we want this and how it changes the behaviour? 

Depending on your answer, I wonder if there are other places we want this logic and if we could consolidate it in a function.

**Comment by borondics** [comment]
Yes, previously the lines went to the middle of the range on top of one
another. This way the initialization is clear and (I think) conveniently
spaced at 10% range far from the data edges.

**Comment by stuart-cls** [comment]
Oh I see, your issue is just in the case of inverted Cut. I like the 10% full range thing!

**Comment by borondics** [comment]
I changed both cuts...

**Comment by stuart-cls** [comment]
Sure, but normal Cut() already set the limits to min()/max()

**Comment by borondics** [comment]
Something happened with the print precision of the Low limit in the cut preprocessor at initialization...

image

**Pull request merged**
