### PR TITLE
[FIX] GSF file reader data indexing

### PR DESCRIPTION
**Pull request by borondics**
- simplified the code so that it uses the same functions as other readers
- fixed the data indexing to be consistent with Gwyddion and NeaSpec orientation
- added tests for checking pixel values

### CODE REVIEW

**Comment by markotoplak** [comment]
Thanks. Travis in complaining because you are missing 3 spaces, but I will not bug you for that.

**Comment by markotoplak** [comment]
Because you were so careful to implement correct data indexing you should verify it with tests. Like test of x and y map positions are fine.

**Comment by borondics** [comment]
This I think is verified by the pixel value. If the indexing gets screwed
up, there is very little chance that the new values will be correct, no?

**Comment by markotoplak** [comment]
Yes, indexing is verified by the pixes value, but the corresponding x and y positions are not. If someone screwed up positioning, these tests would not catch them.

**Comment by borondics** [comment]
OK, I added the tests for the coordinates.

**Pull request merged**
