### PR TITLE
FFT overhaul

### PR DESCRIPTION
**Pull request by stuart-cls**
Status: Review please :)

I am working on an overhaul of the FFT widget / `irfft` module. The main goal of this work is to support using stored phase / stored zpd values. A side benefit is cleaning up the `irfft` module.

- [x] Refactor `irfft` module into a callable class `IRFFT`
- [x] Fix bug in zero fill calculation (with test)
- [x] Implement Mertz Signed / Stored phase / None phase corrections
- [x] For double IFGs, allow selection of just forward or backward scan
- [x] Add an input for stored phase
- [x] Store zpd in phase output, use if on phase input
- [x] Add more zpd peak-search algorithms
- ~Provide user feedback on zpd (i.e. if stored value is being used)~ #250
- ~Allow manual specification of zpd~ #251
- ~Sanity check before averaging forward/backward spectra after FFT~ #252
- ~Handle (and test) multi-spectra stored phase / zpd condition~ #253
- ~Test all the things~ #252

### CODE REVIEW

**Comment by borondics** [comment]
@stuart-cls how is this going?

**Comment by stuart-cls** [comment]
Hi Feri, I put this on hold for a bit to work on other things. I'm hoping to get back to it this fall but no timeline :)

@markotoplak I think it's a bit premature to spend time on a review. Of course if you have any comments I welcome them!

**Comment by stuart-cls** [comment]
Let's do this.

I don't think a settings migration is necessary as I used an `IntEnum` for the new `apod_opts` and `phase_opts` options so `apod_func` and `phase_corr` are backwards compatible.

For the rest of the checklist, I'll make individual issues and tackle them one by one in smaller PRs :P

**Comment by markotoplak** [comment]
Certainly a big improvement, thank you!

**Pull request merged**
