### PR TITLE
PLS: add documentation

### PR DESCRIPTION
**Pull request by ajdapretnar**
Rudimentary documentation for PLS.
Widgets.json is now up to date.

Fixes #524.

### CODE REVIEW

**Comment by borondics** [comment]
Since this widget is in Orange Spectroscopy, I think it would be more practical to use a Spectroscopy dataset (Collagen probably) for the Documentation.

**Comment by markotoplak** [comment]
@ajdapretnar, thanks. Also for keeping widgets.json current!

@borondics, I think that non-spectroscopic data sets are fine here, when this widget is improved, we will move it into Orange3 anyway. Perhaps you can add another example from spectroscopy?

**Comment by ajdapretnar** [comment]
I wanted to do it, but collagen doesn't work (as discussed). Any regression data sets for spectroscopy?

**Comment by stuart-cls** [comment]
@markotoplak @borondics wasn't there an example regression dataset included in the original PLS PR?

**Comment by borondics** [comment]
I think there is...

I'll discuss this issue with @markotoplak live.

**Pull request merged**
